services:
  - type: web
    name: Crop_and_fertilizer_recommendation
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
